"""Shared constants for LifeXP.

Keeping these values outside main.py makes balancing, version bumps, and UI
timing changes easier to find without scrolling through the whole app class.
"""

APP_NAME = "LifeXP"
APP_VERSION = "1.0.4"
GITHUB_REPO = "nimbold/LifeXP"
GITHUB_RELEASES_URL = f"https://github.com/{GITHUB_REPO}/releases"
GITHUB_LATEST_RELEASE_API = f"https://api.github.com/repos/{GITHUB_REPO}/releases/latest"

FONT_SCALE_BASE_SIZE = 11
DEFAULT_FONT_SIZE = 14
MIN_FONT_SIZE = 12
MAX_FONT_SIZE = 17
LEGACY_MAX_FONT_SIZE = 13
PACKAGED_MACOS_MIN_TK_SCALING = 1.333

POPUP_MODE_WITH_PARTICLES = "Popups with particles"
POPUP_MODE_WITHOUT_PARTICLES = "Popups without particles"

BASE_XP_NEEDED = 100
ACCOUNT_BASE_XP_NEEDED = 500
ACCOUNT_LEVEL_CURVE_OFFSET = 81
ACCOUNT_LEVEL_CURVE_FLOOR = 92
ACCOUNT_LEVEL_CURVE_BASE_MULTIPLIER = 0.1
ACCOUNT_LEVEL_CURVE_UPGRADE_MULTIPLIER = 0.02

POPUP_FRAME_INTERVAL_SECONDS = 1 / 60
XP_POPUP_STEPS = 125
XP_POPUP_FADE_STEPS = 42
LEVEL_UP_POPUP_STEPS = 138
LEVEL_UP_POPUP_FADE_STEPS = 36
BATCH_LEVEL_UP_POPUP_STEPS = 190
BATCH_LEVEL_UP_POPUP_FADE_STEPS = 48
RANK_UP_HEADER_FRAMES = 92
TROPHY_POPUP_STEPS = 116
TROPHY_POPUP_FADE_STEPS = 32
XP_TO_REWARD_START_RATIO = 0.68
REWARD_CHAIN_START_RATIO = 0.50
RANK_UP_GLOW_COLOR = "#FFB020"
MAX_ACTIVE_PARTICLES = 180
PARTICLE_HARD_LIFETIME_MS = 2400
PARTICLE_FADE_RELEASE_RATIO = 0.88

